#!/usr/bin/env python3
"""The shared skill documents the two-call credential rotation.

Usage: python3 .github/scripts/check-skill-rotation.py

`kolonie-docs#498`. `kolonie-platform#1683` paused `kolonie.credential.rotate`
behind a confirmation token: the first call returns `confirmation_required` with
`details.confirmationToken`, the second sends that token as `confirm`, and the
current key remains live until that second call returns. The shared body still
said there was no confirmation step, so every generated `SKILL.md` contradicted
the live tool.

This reads `onboarding/skill/body.md` only. The seven generated copies are
downstream of it and are regenerated by each runtime's `skill.yml`; asserting
them here would fail for a reason no commit in this repository can fix until
those pull requests land, which is the same argument `check-skill-description.py`
makes about marketplace listings.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BODY = ROOT / "onboarding" / "skill" / "body.md"

# The claim `#498` was filed about, as a whole clause — not the four words in
# isolation, which a correction that names the old advice would otherwise trip.
STALE = "there is no confirmation step, because"
HEADING = re.compile(r"^###\s+.*leak.*replace.*erase", re.IGNORECASE)

REQUIRED = (
    "kolonie.credential.rotate",
    "first call",
    "confirmation_required",
    "details.confirmationToken",
    "confirm",
    "15 minute",
    "single-use",
    "bound to the presented credential",
    "current key remains live",
    "until the confirmed call returns",
    "second call",
    "shown once",
    "cannot recover",
)


def rotation_section(text: str) -> str | None:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if not HEADING.match(line):
            continue
        end = len(lines)
        for later in range(index + 1, len(lines)):
            if lines[later].startswith("### "):
                end = later
                break
        return "\n".join(lines[index:end])
    return None


def describe() -> Path:
    try:
        return BODY.relative_to(ROOT)
    except ValueError:
        return BODY


def main() -> int:
    label = describe()
    if not BODY.is_file():
        print(f"FAIL {label}: the shared skill body is missing", file=sys.stderr)
        return 1

    section = rotation_section(BODY.read_text(encoding="utf-8"))
    if section is None:
        print(f"FAIL {label}: the credential-rotation section is missing")
        return 1
    folded = " ".join(section.lower().split())

    failed = False
    if STALE in folded:
        print(
            f"FAIL {label} still says there is no confirmation step. "
            "kolonie.credential.rotate is two calls since kolonie-platform#1683; "
            "that sentence now contradicts the live tool (kolonie-docs#498)."
        )
        failed = True

    missing = [needle for needle in REQUIRED if needle.lower() not in folded]
    if missing:
        print(
            f"FAIL {label} does not document the two-call rotation. Missing: "
            + ", ".join(missing)
            + " (kolonie-docs#498)."
        )
        failed = True

    if failed:
        return 1
    print(f"ok   {label} documents the two-call rotation")
    return 0


if __name__ == "__main__":
    sys.exit(main())
